### PR TITLE
docs: Add deployment guide

### PR DESCRIPTION
**Pull request by seung-00**
## Summary
* Set up a CD pipeline with Netlify
* [the url](https://our-blog-starter.netlify.app/)
* [Netlify deployment logs](https://app.netlify.com/sites/our-blog-starter/deploys)

### CODE REVIEW

**Review by jeongnaehyeok — APPROVED** [review]
GOOOOOOOD👍👍

**Review by leeyun1533 — APPROVED** [review]
💯

**Review by jeongshin — COMMENTED** [review]
멋지십니다 ...... !! 👍

**Comment by sungyun6789** [comment]
LGTM!

**Comment by dddieon** [comment]
👍

**Pull request merged**
